### ISSUE TITLE
[Feature Request] Implement GetKeyState

### ISSUE THREAD

**Issue by sbplat** [sbplat/Macro-API#27]
**Is your feature request related to a problem? Please describe.**
There isn't a direct function to determine if a key is pressed or not.

**Describe the solution you'd like**
A function called `GetKeyState` that gets the state of a key. This function should be implemented in `src/common/keyboard.cpp`.

**Describe alternatives you've considered**
`GetKeyStates` returns a map of all the keys and it's a lot of work to just determine the state of a single key.

**Additional context**
Function declaration (see `include/macro/keyboard.h`):
```c++
KeyState GetKeyState(Key key);
```

**Comment by Fireflame213** [comment]
Can I be assigned to this issue?

**Comment by sbplat** [comment]
Sure! I've assigned this issue to you.
