### ISSUE TITLE
[Feature Request] Implement GetButtonState

### ISSUE THREAD

**Issue by sbplat** [sbplat/Macro-API#28]
**Is your feature request related to a problem? Please describe.**
There isn't a direct function to determine if a button is pressed or not.

**Describe the solution you'd like**
A function called `GetButtonState` that gets the state of a button. This function should be implemented in `src/common/mouse.cpp`.

**Describe alternatives you've considered**
`GetButtonStates` returns a map of all the buttons and it's a lot of work to just determine the state of a single button.

**Additional context**
Function declaration (see `include/macro/mouse.h`):
```c++
ButtonState GetButtonState(Button button);
```

**Comment by vaibhavg20comp** [comment]
Hey @sbplat can you assign this issue to me under Hacktoberfest ? If so please label it as Hacktoberfest

**Comment by sbplat** [comment]
> Hey @sbplat can you assign this issue to me under Hacktoberfest ? If so please label it as Hacktoberfest

Sure! I've assigned this issue to you.

I've already opt-in this repository for Hacktoberfest 2022 by labelling it with `hacktoberfest`.

There's no need to add the `hacktoberfest` label to this issue (it's already a part of hacktoberfest).

**Comment by sbplat** [comment]
Hi, I'm going to unassign this issue from you since you haven't worked on it recently.
