### ISSUE TITLE
[Example] Keyboard example for the `Up` and `Down` functions

### ISSUE THREAD

**Issue by sbplat** [sbplat/Macro-API#3]
Create an example using the `Up` and `Down` keyboard functions and place it in the `examples` folder.

Function declarations for `Up` and `Down` (see `include/macro/keyboard.h`):
```c++
void Down(Key key);
void Up(Key key);
```

**Comment by unclebinary1001** [comment]
@sbplat Can I take this up?

**Comment by sbplat** [comment]
Sure! I've assigned this issue to you.

**Comment by unclebinary1001** [comment]
Thank you. Will get started soon.

**Comment by sbplat** [comment]
No problem! Feel free to ask if you have any questions.

**Comment by unclebinary1001** [comment]
Oh okay sure.

**Comment by unclebinary1001** [comment]
So after running: 
`mkdir build && cd build
cmake ..
cmake --build .`

to build code. 

I run executable e.g. examples/click by typing `./examples/click ` in `build` directory. 

I notice that the code executes successfully without any input or interaction. I'm I running it correctly?

**Comment by sbplat** [comment]
You can view the source code of the examples to see what each example does. The `click` example basically clicks using all 5 buttons, with a 1s delay in between each click.

**Comment by unclebinary1001** [comment]
Hello @sbplat . Thank you for your patience with me. I have been able to setup my environment and I was able to run the examples successfully. 

I see that in `tap.cpp` we call functions up and down for example line 6 and line 9:

`Macro::Keyboard::Down(Macro::Keyboard::Key::SHIFT);
...
 Macro::Keyboard::Up(Macro::Keyboard::Key::SHIFT);` 

So just to understand the requirements, do I need to add  more calls for these functions with different parameters  and have them in a separate file for just the `UP` and `DOWN` functions.

**Comment by sbplat** [comment]
No problem! I'm glad that you could run the examples successfully.

You can create a new file for just the `Up` and `Down` functions. Try to be creative and do something cool!

**Comment by unclebinary1001** [comment]
Oh, thank you for letting me be creative with it. So, I initially set up the environment on an Xubuntu virtual machine but its only later when I learnt through the readme that only windows is currently supported, which explained why I was only seeing `Done!` in my terminal lol.

So I created an example that would output a phrase, select and copy it, then paste it twice. 

I was able to implement it. Here's a code snippet. 
```
Macro::Misc::Sleep(2000);
    
    std::cout << "Copy Me Once and Paste Me Twice!";

    Macro::Misc::Sleep(400);
    Macro::Keyboard::Down(Macro::Keyboard::Key::LCTRL);
    Macro::Keyboard::Tap(Macro::Keyboard::Key::A);
    Macro::Keyboard::Up(Macro::Keyboard::Key::LCTRL);

    Macro::Keyboard::Down(Macro::Keyboard::Key::LCTRL);
    Macro::Keyboard::Tap(Macro::Keyboard::Key::INSERT, 40);
    Macro::Keyboard::Up(Macro::Keyboard::Key::LCTRL);

    Macro::Keyboard::Down(Macro::Keyboard::Key::LSHIFT);
    Macro::Keyboard::Tap(Macro::Keyboard::Key::INSERT, 40);
    Macro::Keyboard::Up(Macro::Keyboard::Key::LSHIFT);

    Macro::Keyboard::Down(Macro::Keyboard::Key::LCTRL);
    Macro::Keyboard::Tap(Macro::Keyboard::Key::V, 40);
    Macro::Keyboard::Up(Macro::Keyboard::Key::LCTRL);
```

Is this okay for a pull request for this issue?

**Comment by sbplat** [comment]
Go ahead and submit a PR for this issue.

**Comment by unclebinary1001** [comment]
Oh okay. 

Then is this issue participating in hacktoberfest 2022? 

If it is, can you add the `hacktoberfest` and `hacktoberfest-accepted` label?

**Comment by sbplat** [comment]
I've already opt-in this repository for Hacktoberfest 2022 by labelling it with `hacktoberfest`.

There's no need to add the `hacktoberfest-accepted` label to the PR.

**Comment by unclebinary1001** [comment]
Oh, okay, thanks. Working on PR now.
