### ISSUE TITLE
[Bug] Mouse::MoveAbsolute different on win32 and x11

### ISSUE THREAD

**Issue by sbplat** [sbplat/Macro-API#43]
**Describe the bug**
The `MoveAbsolute` function parameters are different on win32 and x11. Calling the function on win32 and x11 will yield completely different results.
- On win32, the range is from (0, 0) to (65535, 65535).
- On x11, the range is from (0, 0) to (screen_x, screen_y).

**To Reproduce**
The following snippet will move the cursor to the center of the screen on x11 and top left corner on win32.
```c++
MoveAbsolute(screen_x / 2, screen_y / 2);
```

**Expected behavior**
The cursor should move to the center of the screen on all platforms.

**Comment by samuelloza** [comment]
Hi, I send my PR to solve this bug
#44
