### ISSUE TITLE
Want to update README.md file 

### ISSUE THREAD

**Issue by sb-decoder** [sbplat/Macro-API#9]
**Is your feature request related to a problem? Please describe.**
Want to add How to Contribute section and Contributors profiles into README.md file

@sbplat can you assign this to me please?

**Comment by sbplat** [comment]
Sure! I've assigned this issue to you.

**Comment by sbplat** [comment]
There is already a [Contributing Guidelines file](https://github.com/sbplat/Macro-API/blob/main/CONTRIBUTING.md), in case you want to edit that.
